### ISSUE TITLE
Incorrect "git clone" command

### ISSUE THREAD

**Issue by Walt-H** [sourcetoad/DevopsToolKit#2]
Hey guys :)

I was trying to follow your directions to get a personal project to use your kit and noticed that the repo address had a subtle error (as found in step *1*):

`git clone git@github.com:sourcetoad/devop-tools.git` should be
`git clone git@github.com:sourcetoad/DevopsToolKit.git`.

Best,
Walt

**Comment by Walt-H** [comment]
I saw your commit and forgot to mention that this subsequently affects step 2 ;(

**Comment by iBotPeaches** [comment]
Thanks - set it to clone into "devop-tools" to preserve instructions
